# Generated by Django 5.0.4 on 2024-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Image"
            ),
        ),
    ]
