# Generated by Django 5.0.4 on 2024-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("hard", "hard"), ("soft", "soft"), ("spec", "spec")],
                default="soft",
                max_length=4,
                verbose_name="Cover",
            ),
        ),
    ]
